n = int(input())

print(f"1 x {n:.0f} =", n * 1)
print(f"2 x {n:.0f} =", n * 2)
print(f"3 x {n:.0f} =", n * 3)
print(f"4 x {n:.0f} =", n * 4)
print(f"5 x {n:.0f} =", n * 5)
print(f"6 x {n:.0f} =", n * 6)
print(f"7 x {n:.0f} =", n * 7)
print(f"8 x {n:.0f} =", n * 8)
print(f"9 x {n:.0f} =", n * 9)
print(f"10 x {n:.0f} =", n * 10)